export const SET_USER = 'SET_USER'
export const SET_USERS = 'SET_USERS'
export const SET_LOADING = 'SET_LOADING'
export const SET_ERROR = 'SET_ERROR'
export const SET_MESSAGE = 'SET_MESSAGE'
export const SET_AMOUNT = 'SET_AMOUNT'
export const CLEAR_MESSAGE = 'CLEAR_MESSAGE'